// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-realwd/internal/biz"
	"kratos-realwd/internal/conf"
	"kratos-realwd/internal/data"
	"kratos-realwd/internal/server"
	"kratos-realwd/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDb(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db)
	if err != nil {
		return nil, nil, err
	}
	realwdRepo := data.NewRealwdRepo(dataData, logger)
	realwdUsecase := biz.NewRealwdUsecase(realwdRepo, logger)
	realwdService := service.NewRealwdService(realwdUsecase)
	grpcServer := server.NewGRPCServer(confServer, realwdService, logger)
	httpServer := server.NewHTTPServer(confServer, realwdService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
